name: Deploy ImageManager.php to FTPS Server

on:
  push:
    paths:
      - 'ImageManager.php' # Trigger on changes to ImageManager.php

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Upload ImageManager.php via FTPS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTPS_SERVER }}
        username: ${{ secrets.FTPS_USERNAME }}
        password: ${{ secrets.FTPS_PASSWORD }}
        protocol: 'ftps'  # Specify FTPS for secure transfer
        local-dir: './'  # Root directory of the repository, with trailing slash
        server-dir: '/mainecardworks.us.tempcloudsite.com/classes/'  # Path on the FTPS server, with trailing slash
        exclude: |
          *  # Exclude everything
          !ImageManager.php  # Except ImageManager.php