name: Deploy ImageManager.php to FTPS Server

on:
  push:
    paths:
      - 'ImageManager.php' # The path is directly to the root

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Upload ImageManager.php via FTPS
      uses: SamKirkland/FTP-Deploy-Action@4.4.0
      with:
        server: ${{ secrets.FTPS_SERVER }}
        username: ${{ secrets.FTPS_USERNAME }}
        password: ${{ secrets.FTPS_PASSWORD }}
        protocol: 'ftps'  # Specify FTPS for secure transfer
        local-dir: './'  # Root directory of the repository, with trailing slash
        server-dir: '/www/mainecardworks.us.tempcloudsite.com/classes' # Path on the FTPS server
        exclude: |
          *  # Exclude everything by default
        include: |
          ./ImageManager.php  # Include only the ImageManager.php file